# Generated by Django 3.2.9 on 2021-11-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('fee_paid', models.BooleanField(default=True)),
            ],
        ),
    ]
